spring:
  application:
    name: UrlShortner
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

frontend:
  url: http://localhost:4200
KEY_BASE_URL: http://localhost:8080/
URL_SHORTNER_BASE_URL: http://localhost:8081/


# Mysql config (commented out)
# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3308/UrlShortner?serverTimezone=UTC&sslmode=required
#     username: root
#     password: rootpassword
#     driverClassName: com.mysql.cj.jdbc.Driver
#   jpa:
#     hibernate:
#       ddl-auto: update
#     database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8081
  servlet:
    context-path: /urlshortner

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans